steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'task_scheduler_backend'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'task_scheduler_backend'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['function', 'deploy', 'task-scheduler', '--triger-http', '--platform=managed']
