steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    dir: 'task_scheduler_backend/Auth_Service'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'task_scheduler_backend/Auth_Service'

  # Step 2: Deploy the function to Google Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'Auth_Service'
      - '--runtime'
      - 'nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point'
      - 'default'
      - '--region'
      - 'us-central1'
    dir: 'task_scheduler_backend/Auth_Service/dist' 

options:
  logging: 'CLOUD_LOGGING_ONLY'  # Set logging to Cloud Logging only

substitutions:
  _FUNCTION_NAME: 'Auth_Service'
  _ENTRY_POINT: 'default'
  _REGION: 'us-central1'
