steps:
  # Step 1: Install dependencies
  - name: 'node:14'
    dir: 'task_scheduler_backend/Auth_Service'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Deploy the function to Google Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'Auth_Service'
      - '--runtime'
      - 'nodejs14'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point'
      - 'default'
      - '--region'
      - 'us-central1'
      - '--source'
      - 'task_scheduler_backend/Auth_Service'

options:
  logging: 'NONE'  # Set logging to NONE to disable logging

substitutions:
  _FUNCTION_NAME: 'Auth_Service'
  _ENTRY_POINT: 'default'
  _REGION: 'us-central1'
