steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'function-1'
      - '--trigger-http'
      - '--runtime=nodejs20'
      # Optionally add other flags like --region, --entry-point, etc.


